/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.56
 * Generated at: 2022-01-10 07:25:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.error;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class _500_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"robots\" content=\"nofollow\" />\r\n");
      out.write("<meta name=\"CODE_LANGUAGE\" content=\"C#\" />\r\n");
      out.write("<meta name=\"CODE_MADE\" content=\"SK Comms Web Svc Dev Team, Xenes\" />\r\n");
      out.write("<meta name=\"autocomplete\" content=\"off\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"user-scalable=yes, initial-scale = 1.0, width=400\" />\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">	\r\n");
      out.write("<title>네이트</title>\r\n");
      out.write("<link href=\"//main.nateimg.co.kr/img/v7/favicon_32.ico\"  type=\"image/x-icon\" rel=\"shortcut icon\" />\r\n");
      out.write("<style type=\"text/css\"> \r\n");
      out.write("        /* Common */\r\n");
      out.write("        html, body, div, span,\r\n");
      out.write("        h1, h2, h3, h4, h5, h6, p, blockquote, pre,\r\n");
      out.write("        a,  img,  strong, b, u, i, center, dl, dt, dd, ol, ul, li,\r\n");
      out.write("        fieldset, form, label, legend,\r\n");
      out.write("        table, caption, tbody, tfoot, thead, tr, th, td,\r\n");
      out.write("        article, aside, footer, header, hgroup,\r\n");
      out.write("        menu, nav, section,\r\n");
      out.write("        applet, object, iframe, embed, canvas, audio, video {\r\n");
      out.write("            margin:0; padding:0; border:0; font-size:100%; vertical-align:baseline; }\r\n");
      out.write("        html { overflow:auto; }\r\n");
      out.write("        body { background:#fff; line-height:1; } \r\n");
      out.write("        /* HTML5 display-role reset for older browsers */\r\n");
      out.write("        article, aside, details, figcaption, figure,\r\n");
      out.write("        footer, header, hgroup, menu, nav, section {\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("        img { border:0; }\r\n");
      out.write("        li { list-style:none; } \r\n");
      out.write("        /* table */\r\n");
      out.write("        table { table-layout:fixed; border-collapse:collapse; border-spacing:0; }\r\n");
      out.write("        th, td { border-collapse:collapse; }\r\n");
      out.write("        legend, caption, hr { display:none; } \r\n");
      out.write("        /* Form */\r\n");
      out.write("        form { display:inline; }\r\n");
      out.write("        select, input, textarea { color:#666; font-family:'돋움', dotum, verdana, arial, applegothic, sans-serif; font-size:inherit; vertical-align:middle; }\r\n");
      out.write("        fieldset, blockquote, iframe, button { border:none; }\r\n");
      out.write("        /* Font */\r\n");
      out.write("        i, em, u, cite { font-style:normal; } \r\n");
      out.write("        /* Link */\r\n");
      out.write("        a { font-family:'돋움', dotum, verdana, arial, applegothic, sans-serif; font-size:12px; text-decoration:none; }\r\n");
      out.write("        a:hover { text-decoration:underline; }\r\n");
      out.write(" \r\n");
      out.write("        .error_wrap { position:relative; margin:75px auto 0 auto; width:400px; height:390px; background:url('//main.nateimg.co.kr/img/v7/error_nate.png') no-repeat left top; }\r\n");
      out.write("        .error_wrap h1, .error_wrap h2 { text-indent:-9999px; }\r\n");
      out.write("        .error_wrap a { display:block; position:absolute; text-indent:-9999px; overflow:hidden;}\r\n");
      out.write("        .error_wrap a.cs_center { top:206px; left:117px; width:67px; height:16px; }\r\n");
      out.write("        .error_wrap p { text-indent:-9999px; }\r\n");
      out.write("        .error_wrap .btn_prev_page { width:108px; height:27px; left:88px; top:273px; }\r\n");
      out.write("        .error_wrap .btn_go_home { width:120px; height:30px; left:220px; top:273px; }\r\n");
      out.write("        .error_wrap .footer { position:absolute; bottom:0; padding:10px 0 0 0; width:400px; height:40px; border-top:1px solid #f4f8fb; text-align:center; font-family:Verdana; font-size:9px; color:#666; }\r\n");
      out.write("        .error_wrap .footer a { position:relative; text-indent:0; display:inline; color:#F60; text-decoration:none; }\r\n");
      out.write("        .error_wrap .footer a strong { color:#F60; font-family:Verdana; font-size:10px; font-weight:bold; }\r\n");
      out.write("        .error_wrap .footer a strong span { color:#FF2400; font-family:Verdana; font-size:10px; }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write(" \r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"error_wrap\">\r\n");
      out.write("	<h1>NATE</h1>\r\n");
      out.write("	<h2>이용에 불편을 드려 죄송합니다.</h2>\r\n");
      out.write("	<p>\r\n");
      out.write("		잠시 후에 다시 한번 시도해 주시길 부탁 드립니다.\r\n");
      out.write("		동일한 문제가 지속적으로 발생할 경우 네이트/싸이월드 고객센터로 문의하여 주십시오.\r\n");
      out.write("		<a class=\"cs_center\" href=\"http://helpdesk.nate.com\">네이트/싸이월드 고객센터</a>\r\n");
      out.write("	</p>\r\n");
      out.write("	<a class=\"btn_prev_page\"  href=\"javascript:history.back();\">이전 페이지로 가기</a>\r\n");
      out.write("	<a class=\"btn_go_home\" href=\"http://www.nate.com\">네이트 홈으로 가기</a>\r\n");
      out.write("	<div class=\"bottom_wrap\">\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"footer\">\r\n");
      out.write("			Copyright &copy; <a href=\"http://www.skcomms.co.kr\" target=\"_blank\"><strong><span class=\"sk\">SK</span> Communications.</strong></a> All rights reserved.\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
